Feature/core 702 sharing
evannetwork/ui-core-dapps pull request #79
Opened 2019-11-21 13:52 UTC by Tschuck

2019-11-21 14:42 UTC, datrinh requested changes

2019-11-21 14:42 UTC, datrinh commented on dapps/onboarding.vue/src/components/sign-up/sign-up.ts
> +          case 'company': {
You could omit curly brackets in switch/case blocks. Saves some lines :)

2019-11-21 14:42 UTC, datrinh commented on dapps/onboarding.vue/src/components/sign-up/sign-up.ts
> +            required: true,
```suggestion
            required: true
```

2019-11-21 14:42 UTC, datrinh commented on dapps/onboarding.vue/src/components/sign-up/sign-up.ts
> +          label: () => this.$t(`_onboarding.sign-up.alias.${ this.profileForm.accountType.value }`),
```suggestion
          label: () => this.$t(`_onboarding.sign-up.alias.${ this.profileForm.accountType.value }`)
```

2019-11-21 14:42 UTC, datrinh commented on dapps/profile.vue/src/components/verifications/notary/actions/request/request.ts
> +import { bccUtils, } from '@evan.network/ui';
```suggestion
import { bccUtils } from '@evan.network/ui';
```

2019-11-21 14:42 UTC, datrinh commented on dapps/profile.vue/src/components/verifications/notary/actions/request/request.ts
> +    accountName: string,
```suggestion
    accountName: string;
```

2019-11-21 14:42 UTC, datrinh commented on dapps/profile.vue/src/components/verifications/notary/actions/request/request.ts
> +    profileType: string,
```suggestion
    profileType: string;
```

2019-11-21 14:42 UTC, datrinh commented on dapps/profile.vue/src/components/verifications/notary/actions/request/request.ts
> +    profileType: string,
This is minor, but semicolons are better suited in interfaces.

2019-11-21 14:42 UTC, datrinh commented on dapps/profile.vue/src/components/verifications/notary/topic-display/topic-display.ts
> +import { FileHandler, bccUtils, } from '@evan.network/ui';
```suggestion
import { FileHandler, bccUtils } from '@evan.network/ui';
```

2019-11-21 14:43 UTC, datrinh commented
> This pull request **introduces 3 alerts** and **fixes 2** when merging [bc269a2](https://github.com/evannetwork/ui-core-dapps/commit/bc269a2980b9ffa3e456941e2cc72505c5d03351) into [ffa9306](https://github.com/evannetwork/ui-core-dapps/commit/ffa9306cd7e79bb94ea9a2bbe520164292b1ce08) - [view on LGTM.com](https://lgtm.com/projects/g/evannetwork/ui-core-dapps/rev/pr-435e91013642532bc17713d27ff998cef21a126c)
> 
> **new alerts:**
> 
> * 3 for Unused variable, import, function or class
> 
> **fixed alerts:**
> 
> * 2 for Unused variable, import, function or class

Please fix those alerts too :)

2019-11-21 15:24 UTC, datrinh approved these changes

2019-11-22 12:36 UTC, S3bb1 commented on dapps/profile.vue/src/i18n/de.json
> +      "accountDetails": "Identitätinformationen",
```suggestion
      "accountDetails": "Identitätinformationen",
```
```suggestion
      "accountDetails": "Identitätsinformationen",
```

2019-11-22 12:39 UTC, S3bb1 commented on dapps/onboarding.vue/src/i18n/de.json
> +            "desc": "Für Ihren Zugang zu Ihrem Digitaler Zwilling benötigen wir einen Alias und ein Passwort.",
```suggestion
            "desc": "Für den Zugang zu Ihrem Digitalen Zwilling benötigen wir einen Alias und ein Passwort.",
```

2019-11-22 12:40 UTC, S3bb1 requested changes
see comments

2019-11-25 08:36 UTC, S3bb1 approved these changes

2019-11-25 08:37 UTC, merged